server:
  servlet:
    context-path: /demo
  port: 9000
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
albert:
  swagger:
    token_header: uid_token
    base_package: com.albert.lean.swagger.controller
